version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kondus123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FLYWAY_ENABLED: true
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_LOCATIONS: classpath:db/migration
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kondus123
    ports:
      - "5432:5432"


